[graph]
authority   = "https://login.microsoftonline.com/rednexus.onmicrosoft.com" 
tenant_id = "52407292-4ad2-41ab-9edd-3cfa72d7507b"
client_id = "3cc3f418-8b27-48df-9aef-e528978c9df0"
client_secret = "0xF8Q~SbHSbFGAeYCzNUSLFYAb4mfU5n-N-7Waj9"

firmas_share_link = "https://rednexus-my.sharepoint.com/:f:/g/personal/mariolopez_rednexus_onmicrosoft_com/EgB5fHyd5TpMj_IHNHpP7B0B5tH_a08dkNkzfVN9lNLfkA?e=oFByWD"
hostname = "rednexus.sharepoint.com"
site_path  = "/sites/Nexus-Maquinas/"
file_path  = "/Documentos compartidos/Firmas"

[app]
redirect_uri  = "http://localhost:8501/redirect"
admin_group   = "NDM-Admin" #"NDM-Operador"
operator_group= "NDM-Operador"
